// Fish journal data extracted from Cast n Chill Unity assets.
const FISH_DATA = [
  {
    "id": "threadfin-shad",
    "order": 1,
    "en": "Threadfin Shad",
    "zh": "丝鳍鲱鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river1-spot1"
    ],
    "size": "S",
    "sizeZh": "S",
    "length": "4-9 in",
    "lengthZh": "10.2-22.9 cm",
    "weight": "0-0.7 lb",
    "weightZh": "0-0.3 kg",
    "sizeTier": 1,
    "sprite": "game/fish/threadfin-shad.png",
    "thumb": "thumbs/threadfin-shad.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "bluegill-sunfish",
    "order": 2,
    "en": "Bluegill Sunfish",
    "zh": "蓝鳃太阳鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot1",
      "lake1-spot1"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "4-16 in",
    "lengthZh": "10.2-40.6 cm",
    "weight": "0.1-5 lb",
    "weightZh": "0-2.3 kg",
    "sizeTier": 2,
    "sprite": "game/fish/bluegill-sunfish.png",
    "thumb": "thumbs/bluegill-sunfish.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "walleye",
    "order": 3,
    "en": "Walleye",
    "zh": "玻璃梭鲈",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot1"
    ],
    "size": "S / M / L / XL",
    "sizeZh": "S / M / L / XL",
    "length": "10-42 in",
    "lengthZh": "25.4-106.7 cm",
    "weight": "0.5-25 lb",
    "weightZh": "0.2-11.3 kg",
    "sizeTier": 4,
    "sprite": "game/fish/walleye.png",
    "thumb": "thumbs/walleye.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "common-carp",
    "order": 4,
    "en": "Common Carp",
    "zh": "鲤鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "lake1-spot3"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "16-47 in",
    "lengthZh": "40.6-119.4 cm",
    "weight": "4.5-88.4 lb",
    "weightZh": "2-40.1 kg",
    "sizeTier": 5,
    "sprite": "game/fish/common-carp.png",
    "thumb": "thumbs/common-carp.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait03.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "northern-pike",
    "order": 5,
    "en": "Northern Pike",
    "zh": "北方狗鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake1-spot2"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "16-59 in",
    "lengthZh": "40.6-149.9 cm",
    "weight": "2-62.6 lb",
    "weightZh": "0.9-28.4 kg",
    "sizeTier": 5,
    "sprite": "game/fish/northern-pike.png",
    "thumb": "thumbs/northern-pike.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade03.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "muskie",
    "order": 6,
    "en": "Muskie",
    "zh": "北美狗鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "river2-spot1"
    ],
    "size": "L / XL / XXL",
    "sizeZh": "L / XL / XXL",
    "length": "28-72 in",
    "lengthZh": "71.1-182.9 cm",
    "weight": "15-70 lb",
    "weightZh": "6.8-31.8 kg",
    "sizeTier": 5,
    "sprite": "game/fish/muskie.png",
    "thumb": "thumbs/muskie.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon03.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "shorthead-redhorse",
    "order": 7,
    "en": "Shorthead Redhorse",
    "zh": "大鳞吸口鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot3"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "12-24 in",
    "lengthZh": "30.5-61 cm",
    "weight": "1.5-6 lb",
    "weightZh": "0.7-2.7 kg",
    "sizeTier": 3,
    "sprite": "game/fish/shorthead-redhorse.png",
    "thumb": "thumbs/shorthead-redhorse.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "burbot",
    "order": 8,
    "en": "Burbot",
    "zh": "江鳕",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "river1-spot3"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "16-41 in",
    "lengthZh": "40.6-104.1 cm",
    "weight": "1.1-25 lb",
    "weightZh": "0.5-11.3 kg",
    "sizeTier": 4,
    "sprite": "game/fish/burbot.png",
    "thumb": "thumbs/burbot.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "crappie",
    "order": 9,
    "en": "Crappie",
    "zh": "黑花鲗",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river1-spot2"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "7-18 in",
    "lengthZh": "17.8-45.7 cm",
    "weight": "0.2-4.2 lb",
    "weightZh": "0.1-1.9 kg",
    "sizeTier": 2,
    "sprite": "game/fish/crappie.png",
    "thumb": "thumbs/crappie.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon02.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "smallmouth-bass",
    "order": 10,
    "en": "Smallmouth Bass",
    "zh": "小口黑鲈",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river1-spot1"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "9-27 in",
    "lengthZh": "22.9-68.6 cm",
    "weight": "0.4-12 lb",
    "weightZh": "0.2-5.4 kg",
    "sizeTier": 3,
    "sprite": "game/fish/smallmouth-bass.png",
    "thumb": "thumbs/smallmouth-bass.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait02.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "largemouth-bass",
    "order": 11,
    "en": "Largemouth Bass",
    "zh": "大口黑鲈",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot2"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "12-38 in",
    "lengthZh": "30.5-96.5 cm",
    "weight": "1-22.3 lb",
    "weightZh": "0.5-10.1 kg",
    "sizeTier": 4,
    "sprite": "game/fish/largemouth-bass.png",
    "thumb": "thumbs/largemouth-bass.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Jighead",
    "lureZh": "铅头钩",
    "lureIcon": "game/lures/jighead01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "rockbass",
    "order": 12,
    "en": "Rock Bass",
    "zh": "岩钝鲈",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "river1-spot3"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "6-17 in",
    "lengthZh": "15.2-43.2 cm",
    "weight": "0.2-2.8 lb",
    "weightZh": "0.1-1.3 kg",
    "sizeTier": 2,
    "sprite": "game/fish/rockbass.png",
    "thumb": "thumbs/rockbass.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "yellow-perch",
    "order": 13,
    "en": "Yellow Perch",
    "zh": "黄鲈鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "lake1-spot2"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "6-20 in",
    "lengthZh": "15.2-50.8 cm",
    "weight": "0.1-4.2 lb",
    "weightZh": "0-1.9 kg",
    "sizeTier": 2,
    "sprite": "game/fish/yellow-perch.png",
    "thumb": "thumbs/yellow-perch.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Wacky Worm",
    "lureZh": "歪奇虫饵",
    "lureIcon": "game/lures/whacky01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "lake-trout",
    "order": 14,
    "en": "Lake Trout",
    "zh": "湖鳟",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake1-spot1"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "16-60 in",
    "lengthZh": "40.6-152.4 cm",
    "weight": "1.5-70 lb",
    "weightZh": "0.7-31.8 kg",
    "sizeTier": 5,
    "sprite": "game/fish/lake-trout.png",
    "thumb": "thumbs/lake-trout.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner02.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "steelhead-trout",
    "order": 15,
    "en": "Steelhead",
    "zh": "硬头鳟",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot3",
      "ocean1-spot3"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "20-45 in",
    "lengthZh": "50.8-114.3 cm",
    "weight": "2-55 lb",
    "weightZh": "0.9-24.9 kg",
    "sizeTier": 4,
    "sprite": "game/fish/steelhead-trout.png",
    "thumb": "thumbs/steelhead-trout.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner02.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "rainbow-trout",
    "order": 16,
    "en": "Rainbow Trout",
    "zh": "虹鳟鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake1-spot2"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "12-42 in",
    "lengthZh": "30.5-106.7 cm",
    "weight": "1.1-48 lb",
    "weightZh": "0.5-21.8 kg",
    "sizeTier": 4,
    "sprite": "game/fish/rainbow-trout.png",
    "thumb": "thumbs/rainbow-trout.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade02.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "brown-trout",
    "order": 17,
    "en": "Brown Trout",
    "zh": "褐鳟",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river1-spot1",
      "river1-spot2"
    ],
    "size": "S / M / L / XL",
    "sizeZh": "S / M / L / XL",
    "length": "6-44 in",
    "lengthZh": "15.2-111.8 cm",
    "weight": "0.2-41 lb",
    "weightZh": "0.1-18.6 kg",
    "sizeTier": 4,
    "sprite": "game/fish/brown-trout.png",
    "thumb": "thumbs/brown-trout.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait02.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "brook-trout",
    "order": 18,
    "en": "Brook Trout",
    "zh": "溪鳟",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river2-spot1"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "6-31 in",
    "lengthZh": "15.2-78.7 cm",
    "weight": "0.5-14 lb",
    "weightZh": "0.2-6.4 kg",
    "sizeTier": 3,
    "sprite": "game/fish/brook-trout.png",
    "thumb": "thumbs/brook-trout.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Topwater",
    "lureZh": "水面饵",
    "lureIcon": "game/lures/topwater01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "tiger-trout",
    "order": 19,
    "en": "Tiger Trout",
    "zh": "虎纹鳟鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "lake1-spot2",
      "lake1-spot1"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "10-28 in",
    "lengthZh": "25.4-71.1 cm",
    "weight": "0.8-13 lb",
    "weightZh": "0.4-5.9 kg",
    "sizeTier": 3,
    "sprite": "game/fish/tiger-trout.png",
    "thumb": "thumbs/tiger-trout.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "cutthroat-trout",
    "order": 20,
    "en": "Cutthroat Trout",
    "zh": "割喉鳟",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "river2-spot2"
    ],
    "size": "S / M / L / XL",
    "sizeZh": "S / M / L / XL",
    "length": "8-39 in",
    "lengthZh": "20.3-99.1 cm",
    "weight": "0.4-41 lb",
    "weightZh": "0.2-18.6 kg",
    "sizeTier": 4,
    "sprite": "game/fish/cutthroat-trout.png",
    "thumb": "thumbs/cutthroat-trout.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner02.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "arctic-char",
    "order": 21,
    "en": "Arctic Char",
    "zh": "北极红点鲑",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake1-spot3"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "12-36 in",
    "lengthZh": "30.5-91.4 cm",
    "weight": "1.1-20 lb",
    "weightZh": "0.5-9.1 kg",
    "sizeTier": 3,
    "sprite": "game/fish/arctic-char.png",
    "thumb": "thumbs/arctic-char.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "arctic-grayling",
    "order": 22,
    "en": "Arctic Grayling",
    "zh": "北极茴鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "river2-spot2"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "12-30 in",
    "lengthZh": "30.5-76.2 cm",
    "weight": "0.3-8.4 lb",
    "weightZh": "0.1-3.8 kg",
    "sizeTier": 3,
    "sprite": "game/fish/arctic-grayling.png",
    "thumb": "thumbs/arctic-grayling.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "cisco",
    "order": 23,
    "en": "Cisco",
    "zh": "白鲑鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake1-spot2"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "6-16 in",
    "lengthZh": "15.2-40.6 cm",
    "weight": "0.2-2 lb",
    "weightZh": "0.1-0.9 kg",
    "sizeTier": 2,
    "sprite": "game/fish/cisco.png",
    "thumb": "thumbs/cisco.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "lake-whitefish",
    "order": 24,
    "en": "Lake Whitefish",
    "zh": "湖白鲑",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "lake1-spot1"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "9-39 in",
    "lengthZh": "22.9-99.1 cm",
    "weight": "0.5-15 lb",
    "weightZh": "0.2-6.8 kg",
    "sizeTier": 3,
    "sprite": "game/fish/lake-whitefish.png",
    "thumb": "thumbs/lake-whitefish.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Wacky Worm",
    "lureZh": "歪奇虫饵",
    "lureIcon": "game/lures/whacky01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "round-whitefish",
    "order": 25,
    "en": "Round Whitefish",
    "zh": "真柱白鲑",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "lake1-spot3"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "8-19 in",
    "lengthZh": "20.3-48.3 cm",
    "weight": "0.3-4 lb",
    "weightZh": "0.1-1.8 kg",
    "sizeTier": 2,
    "sprite": "game/fish/round-whitefish.png",
    "thumb": "thumbs/round-whitefish.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "mountain-whitefish",
    "order": 26,
    "en": "Mountain Whitefish",
    "zh": "山地柱白鲑",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river2-spot1"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "8-28 in",
    "lengthZh": "20.3-71.1 cm",
    "weight": "0.3-6.4 lb",
    "weightZh": "0.1-2.9 kg",
    "sizeTier": 3,
    "sprite": "game/fish/mountain-whitefish.png",
    "thumb": "thumbs/mountain-whitefish.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Topwater",
    "lureZh": "水面饵",
    "lureIcon": "game/lures/topwater01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "longnose-sucker",
    "order": 27,
    "en": "Longnose Sucker",
    "zh": "真亚口鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot2"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "8-25 in",
    "lengthZh": "20.3-63.5 cm",
    "weight": "0.5-5 lb",
    "weightZh": "0.2-2.3 kg",
    "sizeTier": 2,
    "sprite": "game/fish/longnose-sucker.png",
    "thumb": "thumbs/longnose-sucker.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "white-sucker",
    "order": 28,
    "en": "White Sucker",
    "zh": "康氏亚口鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "lake1-spot3"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "8-23 in",
    "lengthZh": "20.3-58.4 cm",
    "weight": "0.9-6.8 lb",
    "weightZh": "0.4-3.1 kg",
    "sizeTier": 3,
    "sprite": "game/fish/white-sucker.png",
    "thumb": "thumbs/white-sucker.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "mooneye",
    "order": 29,
    "en": "Mooneye",
    "zh": "背甲月眼鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "lake1-spot1"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "8-18 in",
    "lengthZh": "20.3-45.7 cm",
    "weight": "0.3-2.3 lb",
    "weightZh": "0.1-1 kg",
    "sizeTier": 2,
    "sprite": "game/fish/mooneye.png",
    "thumb": "thumbs/mooneye.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "goldeye",
    "order": 30,
    "en": "Goldeye",
    "zh": "似鲱月眼鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "lake1-spot3"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "10-19 in",
    "lengthZh": "25.4-48.3 cm",
    "weight": "0.5-4 lb",
    "weightZh": "0.2-1.8 kg",
    "sizeTier": 2,
    "sprite": "game/fish/goldeye.png",
    "thumb": "thumbs/goldeye.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "creek-chub",
    "order": 31,
    "en": "Creek Chub",
    "zh": "黑斑须雅罗鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot3"
    ],
    "size": "S",
    "sizeZh": "S",
    "length": "4-12 in",
    "lengthZh": "10.2-30.5 cm",
    "weight": "0-0.7 lb",
    "weightZh": "0-0.3 kg",
    "sizeTier": 1,
    "sprite": "game/fish/creek-chub.png",
    "thumb": "thumbs/creek-chub.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "bullhead-catfish",
    "order": 32,
    "en": "Bullhead Catfish",
    "zh": "牛头鲶鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river1-spot2"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "7-21 in",
    "lengthZh": "17.8-53.3 cm",
    "weight": "0.9-6 lb",
    "weightZh": "0.4-2.7 kg",
    "sizeTier": 3,
    "sprite": "game/fish/bullhead-catfish.png",
    "thumb": "thumbs/bullhead-catfish.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "longnose-dace",
    "order": 33,
    "en": "Longnose Dace",
    "zh": "长吻鲦鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river2-spot2"
    ],
    "size": "S",
    "sizeZh": "S",
    "length": "3-7 in",
    "lengthZh": "7.6-17.8 cm",
    "weight": "0-0.1 lb",
    "weightZh": "0-0 kg",
    "sizeTier": 1,
    "sprite": "game/fish/longnose-dace.png",
    "thumb": "thumbs/longnose-dace.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "eulachon",
    "order": 34,
    "en": "Eulachon",
    "zh": "蜡鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "ocean2-spot1"
    ],
    "size": "S",
    "sizeZh": "S",
    "length": "6-12 in",
    "lengthZh": "15.2-30.5 cm",
    "weight": "0.1-0.3 lb",
    "weightZh": "0-0.1 kg",
    "sizeTier": 1,
    "sprite": "game/fish/eulachon.png",
    "thumb": "thumbs/eulachon.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "capelin",
    "order": 35,
    "en": "Capelin",
    "zh": "多春鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "ocean2-spot2"
    ],
    "size": "S",
    "sizeZh": "S",
    "length": "6-10 in",
    "lengthZh": "15.2-25.4 cm",
    "weight": "0-0.1 lb",
    "weightZh": "0-0 kg",
    "sizeTier": 1,
    "sprite": "game/fish/capelin.png",
    "thumb": "thumbs/capelin.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "pacific-herring",
    "order": 36,
    "en": "Pacific Herring",
    "zh": "太平洋鲱",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "ocean1-spot1",
      "ocean1-spot2"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "6-18 in",
    "lengthZh": "15.2-45.7 cm",
    "weight": "0.1-1.1 lb",
    "weightZh": "0-0.5 kg",
    "sizeTier": 2,
    "sprite": "game/fish/pacific-herring.png",
    "thumb": "thumbs/pacific-herring.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "american-shad",
    "order": 37,
    "en": "American Shad",
    "zh": "美洲西鲱",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "ocean1-spot1",
      "ocean1-spot3"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "16-30 in",
    "lengthZh": "40.6-76.2 cm",
    "weight": "2-11 lb",
    "weightZh": "0.9-5 kg",
    "sizeTier": 3,
    "sprite": "game/fish/american-shad.png",
    "thumb": "thumbs/american-shad.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber02.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "atlantic-salmon",
    "order": 38,
    "en": "Atlantic Salmon",
    "zh": "大西洋鲑",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ocean1-spot1",
      "ocean1-spot3"
    ],
    "size": "L / XL / XXL",
    "sizeZh": "L / XL / XXL",
    "length": "21-59 in",
    "lengthZh": "53.3-149.9 cm",
    "weight": "5-103 lb",
    "weightZh": "2.3-46.7 kg",
    "sizeTier": 5,
    "sprite": "game/fish/atlantic-salmon.png",
    "thumb": "thumbs/atlantic-salmon.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait03.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "chinook-salmon",
    "order": 39,
    "en": "King Salmon",
    "zh": "帝王鲑",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ocean1-spot2",
      "ocean1-spot3"
    ],
    "size": "L / XL / XXL",
    "sizeZh": "L / XL / XXL",
    "length": "24-58 in",
    "lengthZh": "61-147.3 cm",
    "weight": "10-126 lb",
    "weightZh": "4.5-57.2 kg",
    "sizeTier": 5,
    "sprite": "game/fish/chinook-salmon.png",
    "thumb": "thumbs/chinook-salmon.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Glidebait",
    "lureZh": "滑动饵",
    "lureIcon": "game/lures/glide02.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "coho-salmon",
    "order": 40,
    "en": "Coho Salmon",
    "zh": "银鲑",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river2-spot1",
      "ocean1-spot2"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "12-42 in",
    "lengthZh": "30.5-106.7 cm",
    "weight": "2-33 lb",
    "weightZh": "0.9-15 kg",
    "sizeTier": 4,
    "sprite": "game/fish/coho-salmon.png",
    "thumb": "thumbs/coho-salmon.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Jighead",
    "lureZh": "铅头钩",
    "lureIcon": "game/lures/jighead01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "sockeye-salmon",
    "order": 41,
    "en": "Sockeye Salmon",
    "zh": "红鲑",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "river2-spot2",
      "ocean2-spot1"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "20-31 in",
    "lengthZh": "50.8-78.7 cm",
    "weight": "4-16 lb",
    "weightZh": "1.8-7.3 kg",
    "sizeTier": 3,
    "sprite": "game/fish/sockeye-salmon.png",
    "thumb": "thumbs/sockeye-salmon.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon02.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "pink-salmon",
    "order": 42,
    "en": "Pink Salmon",
    "zh": "粉鲑",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ocean1-spot3"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "18-31 in",
    "lengthZh": "45.7-78.7 cm",
    "weight": "2.5-15 lb",
    "weightZh": "1.1-6.8 kg",
    "sizeTier": 3,
    "sprite": "game/fish/pink-salmon.png",
    "thumb": "thumbs/pink-salmon.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Glidebait",
    "lureZh": "滑动饵",
    "lureIcon": "game/lures/glide01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "chum-salmon",
    "order": 43,
    "en": "Chum Salmon",
    "zh": "秋鲑",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "river2-spot1",
      "ocean2-spot2"
    ],
    "size": "L / XL",
    "sizeZh": "L / XL",
    "length": "20-35 in",
    "lengthZh": "50.8-88.9 cm",
    "weight": "6-35 lb",
    "weightZh": "2.7-15.9 kg",
    "sizeTier": 4,
    "sprite": "game/fish/chum-salmon.png",
    "thumb": "thumbs/chum-salmon.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Jighead",
    "lureZh": "铅头钩",
    "lureIcon": "game/lures/jighead01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "masu-salmon",
    "order": 44,
    "en": "Masu Salmon",
    "zh": "马苏鲑",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "river2-spot2",
      "ocean1-spot2"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "16-28 in",
    "lengthZh": "40.6-71.1 cm",
    "weight": "3-20 lb",
    "weightZh": "1.4-9.1 kg",
    "sizeTier": 3,
    "sprite": "game/fish/masu-salmon.png",
    "thumb": "thumbs/masu-salmon.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon02.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "dolly-varden",
    "order": 45,
    "en": "Dolly Varden",
    "zh": "花羔红点鲑",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ocean2-spot1",
      "ocean2-spot2"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "12-40 in",
    "lengthZh": "30.5-101.6 cm",
    "weight": "1.1-21 lb",
    "weightZh": "0.5-9.5 kg",
    "sizeTier": 4,
    "sprite": "game/fish/dolly-varden.png",
    "thumb": "thumbs/dolly-varden.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner02.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "lingcod",
    "order": 46,
    "en": "Lingcod",
    "zh": "蛇鳕",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ocean1-spot1",
      "ocean1-spot2"
    ],
    "size": "L / XL / XXL",
    "sizeZh": "L / XL / XXL",
    "length": "24-60 in",
    "lengthZh": "61-152.4 cm",
    "weight": "10-86 lb",
    "weightZh": "4.5-39 kg",
    "sizeTier": 5,
    "sprite": "game/fish/lingcod.png",
    "thumb": "thumbs/lingcod.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Jighead",
    "lureZh": "铅头钩",
    "lureIcon": "game/lures/jighead02.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "greenland-halibut",
    "order": 47,
    "en": "Greenland Halibut",
    "zh": "格陵兰比目鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ocean2-spot2"
    ],
    "size": "XL / XXL",
    "sizeZh": "XL / XXL",
    "length": "31-51 in",
    "lengthZh": "78.7-129.5 cm",
    "weight": "24-99 lb",
    "weightZh": "10.9-44.9 kg",
    "sizeTier": 5,
    "sprite": "game/fish/greenland-halibut.png",
    "thumb": "thumbs/greenland-halibut.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade03.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "pacific-halibut",
    "order": 48,
    "en": "Pacific Halibut",
    "zh": "太平洋比目鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ocean2-spot1"
    ],
    "size": "XL / XXL",
    "sizeZh": "XL / XXL",
    "length": "32-96 in",
    "lengthZh": "81.3-243.8 cm",
    "weight": "20-500 lb",
    "weightZh": "9.1-226.8 kg",
    "sizeTier": 5,
    "sprite": "game/fish/pacific-halibut.png",
    "thumb": "thumbs/pacific-halibut.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade03.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "yelloweye-rockfish",
    "order": 49,
    "en": "Yelloweye Rockfish",
    "zh": "锉头平鲉",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ocean1-spot1"
    ],
    "size": "L / XL",
    "sizeZh": "L / XL",
    "length": "16-41 in",
    "lengthZh": "40.6-104.1 cm",
    "weight": "5-39 lb",
    "weightZh": "2.3-17.7 kg",
    "sizeTier": 4,
    "sprite": "game/fish/yelloweye-rockfish.png",
    "thumb": "thumbs/yelloweye-rockfish.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "striped-bass",
    "order": 50,
    "en": "Striped Bass",
    "zh": "条纹鲈",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ocean2-spot1",
      "ocean2-spot2"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "20-54 in",
    "lengthZh": "50.8-137.2 cm",
    "weight": "3-81 lb",
    "weightZh": "1.4-36.7 kg",
    "sizeTier": 5,
    "sprite": "game/fish/striped-bass.png",
    "thumb": "thumbs/striped-bass.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait03.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "channel-catfish",
    "order": 51,
    "en": "Channel Catfish",
    "zh": "叉尾鲶鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "lake2-spot1"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "20-58 in",
    "lengthZh": "50.8-147.3 cm",
    "weight": "2.8-62 lb",
    "weightZh": "1.3-28.1 kg",
    "sizeTier": 5,
    "sprite": "game/fish/channel-catfish.png",
    "thumb": "thumbs/channel-catfish.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot02.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "white-bass",
    "order": 52,
    "en": "White Bass",
    "zh": "白鲈",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "lake2-spot1"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "10-20 in",
    "lengthZh": "25.4-50.8 cm",
    "weight": "0.5-4 lb",
    "weightZh": "0.2-1.8 kg",
    "sizeTier": 2,
    "sprite": "game/fish/white-bass.png",
    "thumb": "thumbs/white-bass.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait01.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "hybrid-striped-bass",
    "order": 53,
    "en": "Hybrid Striped Bass",
    "zh": "杂交条纹鲈",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake2-spot1"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "17-30 in",
    "lengthZh": "43.2-76.2 cm",
    "weight": "3-18 lb",
    "weightZh": "1.4-8.2 kg",
    "sizeTier": 3,
    "sprite": "game/fish/hybrid-striped-bass.png",
    "thumb": "thumbs/hybrid-striped-bass.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Jighead",
    "lureZh": "铅头钩",
    "lureIcon": "game/lures/jighead01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "humpback-whitefish",
    "order": 54,
    "en": "Humpback Whitefish",
    "zh": "驼背白鲑",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake2-spot2"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "10-24 in",
    "lengthZh": "25.4-61 cm",
    "weight": "0.9-7 lb",
    "weightZh": "0.4-3.2 kg",
    "sizeTier": 3,
    "sprite": "game/fish/humpback-whitefish.png",
    "thumb": "thumbs/humpback-whitefish.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "peamouth",
    "order": 55,
    "en": "Peamouth",
    "zh": "豆口鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "lake2-spot1",
      "lake2-spot2"
    ],
    "size": "S",
    "sizeZh": "S",
    "length": "8-14 in",
    "lengthZh": "20.3-35.6 cm",
    "weight": "0.2-1 lb",
    "weightZh": "0.1-0.5 kg",
    "sizeTier": 1,
    "sprite": "game/fish/peamouth.png",
    "thumb": "thumbs/peamouth.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Bobber",
    "lureZh": "浮漂",
    "lureIcon": "game/lures/bobber01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "largescale-sucker",
    "order": 56,
    "en": "Largescale Sucker",
    "zh": "大鳞亚口鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake2-spot2"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "10-70 in",
    "lengthZh": "25.4-177.8 cm",
    "weight": "1-9 lb",
    "weightZh": "0.5-4.1 kg",
    "sizeTier": 3,
    "sprite": "game/fish/largescale-sucker.png",
    "thumb": "thumbs/largescale-sucker.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "northern-pikeminnow",
    "order": 57,
    "en": "Northern Pikeminnow",
    "zh": "北方梭鲤",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "lake2-spot1",
      "lake2-spot2"
    ],
    "size": "S / M / L / XL",
    "sizeZh": "S / M / L / XL",
    "length": "10-25 in",
    "lengthZh": "25.4-63.5 cm",
    "weight": "0.6-28 lb",
    "weightZh": "0.3-12.7 kg",
    "sizeTier": 4,
    "sprite": "game/fish/northern-pikeminnow.png",
    "thumb": "thumbs/northern-pikeminnow.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Swimbait",
    "lureZh": "游动饵",
    "lureIcon": "game/lures/swim02.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "white-sturgeon",
    "order": 58,
    "en": "White Sturgeon",
    "zh": "白鲟",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "lake2-spot2"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "20-94 in",
    "lengthZh": "50.8-238.8 cm",
    "weight": "2-259 lb",
    "weightZh": "0.9-117.5 kg",
    "sizeTier": 5,
    "sprite": "game/fish/white-sturgeon.png",
    "thumb": "thumbs/white-sturgeon.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Swimbait",
    "lureZh": "游动饵",
    "lureIcon": "game/lures/swim02.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "ice-walleye",
    "order": 59,
    "en": "Walleye",
    "zh": "玻璃梭鲈",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ice1-spot1"
    ],
    "size": "S / M / L / XL",
    "sizeZh": "S / M / L / XL",
    "length": "10-42 in",
    "lengthZh": "25.4-106.7 cm",
    "weight": "0.5-25 lb",
    "weightZh": "0.2-11.3 kg",
    "sizeTier": 4,
    "sprite": "game/fish/ice-walleye.png",
    "thumb": "thumbs/ice-walleye.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  },
  {
    "id": "ice-northern-pike",
    "order": 60,
    "en": "Northern Pike",
    "zh": "北方狗鱼",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ice1-spot1"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "16-53 in",
    "lengthZh": "40.6-134.6 cm",
    "weight": "2-53 lb",
    "weightZh": "0.9-24 kg",
    "sizeTier": 4,
    "sprite": "game/fish/ice-northern-pike.png",
    "thumb": "thumbs/ice-northern-pike.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade02.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "ice-muskie",
    "order": 61,
    "en": "Muskie",
    "zh": "北美狗鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ice1-spot1"
    ],
    "size": "L / XL",
    "sizeZh": "L / XL",
    "length": "28-65 in",
    "lengthZh": "71.1-165.1 cm",
    "weight": "15-60 lb",
    "weightZh": "6.8-27.2 kg",
    "sizeTier": 4,
    "sprite": "game/fish/ice-muskie.png",
    "thumb": "thumbs/ice-muskie.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spoonbait",
    "lureZh": "匙型饵",
    "lureIcon": "game/lures/spoon01.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "ice-tiger-muskie",
    "order": 62,
    "en": "Tiger Muskie",
    "zh": "虎纹狗鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ice1-spot1"
    ],
    "size": "M / L / XL / XXL",
    "sizeZh": "M / L / XL / XXL",
    "length": "20-69 in",
    "lengthZh": "50.8-175.3 cm",
    "weight": "1.5-64 lb",
    "weightZh": "0.7-29 kg",
    "sizeTier": 5,
    "sprite": "game/fish/ice-tiger-muskie.png",
    "thumb": "thumbs/ice-tiger-muskie.png",
    "rod": "Grizzly Pole",
    "rodZh": "灰熊柱杆",
    "rodIcon": "game/rods/cropped/rod07.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait03.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "ice-smallmouth-bass",
    "order": 63,
    "en": "Smallmouth Bass",
    "zh": "小口黑鲈",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "ice1-spot1"
    ],
    "size": "S / M / L",
    "sizeZh": "S / M / L",
    "length": "9-27 in",
    "lengthZh": "22.9-68.6 cm",
    "weight": "0.4-12 lb",
    "weightZh": "0.2-5.4 kg",
    "sizeTier": 3,
    "sprite": "game/fish/ice-smallmouth-bass.png",
    "thumb": "thumbs/ice-smallmouth-bass.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Crankbait",
    "lureZh": "曲柄饵",
    "lureIcon": "game/lures/crankbait02.png",
    "timeIcons": [
      "night"
    ],
    "timeZh": "晚上",
    "time": "Night"
  },
  {
    "id": "ice-largemouth-bass",
    "order": 64,
    "en": "Largemouth Bass",
    "zh": "大口黑鲈",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ice1-spot1"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "12-38 in",
    "lengthZh": "30.5-96.5 cm",
    "weight": "1-22.3 lb",
    "weightZh": "0.5-10.1 kg",
    "sizeTier": 4,
    "sprite": "game/fish/ice-largemouth-bass.png",
    "thumb": "thumbs/ice-largemouth-bass.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Jighead",
    "lureZh": "铅头钩",
    "lureIcon": "game/lures/jighead01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "ice-yellow-perch",
    "order": 65,
    "en": "Yellow Perch",
    "zh": "黄鲈鱼",
    "rarity": "Rare",
    "rarityZh": "稀有",
    "rarityId": "rare",
    "locations": [
      "ice1-spot1"
    ],
    "size": "S / M",
    "sizeZh": "S / M",
    "length": "6-20 in",
    "lengthZh": "15.2-50.8 cm",
    "weight": "0.1-4.2 lb",
    "weightZh": "0-1.9 kg",
    "sizeTier": 2,
    "sprite": "game/fish/ice-yellow-perch.png",
    "thumb": "thumbs/ice-yellow-perch.png",
    "rod": "Lil' Guppy",
    "rodZh": "小古比",
    "rodIcon": "game/rods/cropped/rod01.png",
    "lure": "Wacky Worm",
    "lureZh": "歪奇虫饵",
    "lureIcon": "game/lures/whacky01.png",
    "timeIcons": [
      "dusk"
    ],
    "timeZh": "傍晚",
    "time": "Dusk"
  },
  {
    "id": "ice-lake-trout",
    "order": 66,
    "en": "Lake Trout",
    "zh": "湖鳟",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ice1-spot1"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "16-50 in",
    "lengthZh": "40.6-127 cm",
    "weight": "1.5-55 lb",
    "weightZh": "0.7-24.9 kg",
    "sizeTier": 4,
    "sprite": "game/fish/ice-lake-trout.png",
    "thumb": "thumbs/ice-lake-trout.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Spinnerbait",
    "lureZh": "旋转亮片饵",
    "lureIcon": "game/lures/spinner02.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "ice-channel-catfish",
    "order": 67,
    "en": "Channel Catfish",
    "zh": "叉尾鲶鱼",
    "rarity": "Common",
    "rarityZh": "常见",
    "rarityId": "common",
    "locations": [
      "ice1-spot1"
    ],
    "size": "M / L / XL",
    "sizeZh": "M / L / XL",
    "length": "20-44 in",
    "lengthZh": "50.8-111.8 cm",
    "weight": "2.8-58 lb",
    "weightZh": "1.3-26.3 kg",
    "sizeTier": 4,
    "sprite": "game/fish/ice-channel-catfish.png",
    "thumb": "thumbs/ice-channel-catfish.png",
    "rod": "Timberjack",
    "rodZh": "伐木工杆",
    "rodIcon": "game/rods/cropped/rod06.png",
    "lure": "Dropshot",
    "lureZh": "倒钓钓组",
    "lureIcon": "game/lures/dropshot02.png",
    "timeIcons": [
      "dawn"
    ],
    "timeZh": "早晨",
    "time": "Dawn"
  },
  {
    "id": "ice-arctic-char",
    "order": 68,
    "en": "Arctic Char",
    "zh": "北极红点鲑",
    "rarity": "Uncommon",
    "rarityZh": "罕见",
    "rarityId": "uncommon",
    "locations": [
      "ice1-spot1"
    ],
    "size": "M / L",
    "sizeZh": "M / L",
    "length": "12-36 in",
    "lengthZh": "30.5-91.4 cm",
    "weight": "1.1-20 lb",
    "weightZh": "0.5-9.1 kg",
    "sizeTier": 3,
    "sprite": "game/fish/ice-arctic-char.png",
    "thumb": "thumbs/ice-arctic-char.png",
    "rod": "Maple Scout",
    "rodZh": "枫林侦察兵",
    "rodIcon": "game/rods/cropped/rod02.png",
    "lure": "Bladebait",
    "lureZh": "刀饵",
    "lureIcon": "game/lures/blade01.png",
    "timeIcons": [
      "day"
    ],
    "timeZh": "中午",
    "time": "Day"
  }
];

const LOCATION_GROUPS = [
  {
    "id": "river1-spot1",
    "order": 1,
    "areaId": "river1",
    "area": "Goldenfork River",
    "areaZh": "金叉河",
    "spot": "The Fork",
    "spotZh": "分岔口",
    "fish": [
      "threadfin-shad",
      "smallmouth-bass",
      "walleye",
      "bluegill-sunfish",
      "brown-trout"
    ],
    "ice": false
  },
  {
    "id": "river1-spot2",
    "order": 2,
    "areaId": "river1",
    "area": "Goldenfork River",
    "areaZh": "金叉河",
    "spot": "Beaver Dam",
    "spotZh": "海狸坝",
    "fish": [
      "largemouth-bass",
      "bullhead-catfish",
      "longnose-sucker",
      "brown-trout",
      "crappie"
    ],
    "ice": false
  },
  {
    "id": "river1-spot3",
    "order": 3,
    "areaId": "river1",
    "area": "Goldenfork River",
    "areaZh": "金叉河",
    "spot": "The Mistwood",
    "spotZh": "迷雾林",
    "fish": [
      "shorthead-redhorse",
      "rockbass",
      "burbot",
      "steelhead-trout",
      "creek-chub"
    ],
    "ice": false
  },
  {
    "id": "river2-spot1",
    "order": 4,
    "areaId": "river2",
    "area": "Grizzlyridge River",
    "areaZh": "灰岭河",
    "spot": "The Rapids",
    "spotZh": "急流区",
    "fish": [
      "muskie",
      "mountain-whitefish",
      "brook-trout",
      "chum-salmon",
      "coho-salmon"
    ],
    "ice": false
  },
  {
    "id": "river2-spot2",
    "order": 5,
    "areaId": "river2",
    "area": "Grizzlyridge River",
    "areaZh": "灰岭河",
    "spot": "Eagles Nest",
    "spotZh": "鹰巢",
    "fish": [
      "cutthroat-trout",
      "arctic-grayling",
      "sockeye-salmon",
      "longnose-dace",
      "masu-salmon"
    ],
    "ice": false
  },
  {
    "id": "lake1-spot2",
    "order": 6,
    "areaId": "lake1",
    "area": "Fawnmirror Lake",
    "areaZh": "鹿镜湖",
    "spot": "Underwater Meadow",
    "spotZh": "水下草甸",
    "fish": [
      "northern-pike",
      "cisco",
      "tiger-trout",
      "rainbow-trout",
      "yellow-perch"
    ],
    "ice": false
  },
  {
    "id": "lake1-spot1",
    "order": 7,
    "areaId": "lake1",
    "area": "Fawnmirror Lake",
    "areaZh": "鹿镜湖",
    "spot": "Picnic Point",
    "spotZh": "野餐点",
    "fish": [
      "lake-whitefish",
      "lake-trout",
      "mooneye",
      "bluegill-sunfish",
      "tiger-trout"
    ],
    "ice": false
  },
  {
    "id": "lake1-spot3",
    "order": 8,
    "areaId": "lake1",
    "area": "Fawnmirror Lake",
    "areaZh": "鹿镜湖",
    "spot": "Fisherman's Rest",
    "spotZh": "渔夫憩所",
    "fish": [
      "goldeye",
      "arctic-char",
      "white-sucker",
      "round-whitefish",
      "common-carp"
    ],
    "ice": false
  },
  {
    "id": "lake2-spot1",
    "order": 9,
    "areaId": "lake2",
    "area": "Autumnwood Lake",
    "areaZh": "秋林湖",
    "spot": "Shallows Edge",
    "spotZh": "浅滩界",
    "fish": [
      "northern-pikeminnow",
      "channel-catfish",
      "hybrid-striped-bass",
      "white-bass",
      "peamouth"
    ],
    "ice": false
  },
  {
    "id": "lake2-spot2",
    "order": 10,
    "areaId": "lake2",
    "area": "Autumnwood Lake",
    "areaZh": "秋林湖",
    "spot": "Otter Cove",
    "spotZh": "水獭湾",
    "fish": [
      "northern-pikeminnow",
      "largescale-sucker",
      "white-sturgeon",
      "peamouth",
      "humpback-whitefish"
    ],
    "ice": false
  },
  {
    "id": "cabin1",
    "order": 11,
    "areaId": "cabin1",
    "area": "Old Moose Valley",
    "areaZh": "老驼鹿谷",
    "spot": "Old Moose Cabin",
    "spotZh": "老麋鹿小屋",
    "fish": [],
    "ice": false
  },
  {
    "id": "ocean1-spot1",
    "order": 12,
    "areaId": "ocean1",
    "area": "Icewater Sea ",
    "areaZh": "冰水海",
    "spot": "Watchers Point",
    "spotZh": "守望角",
    "fish": [
      "atlantic-salmon",
      "pacific-herring",
      "american-shad",
      "lingcod",
      "yelloweye-rockfish"
    ],
    "ice": false
  },
  {
    "id": "ocean1-spot2",
    "order": 13,
    "areaId": "ocean1",
    "area": "Icewater Sea ",
    "areaZh": "冰水海",
    "spot": "Craggy Reef",
    "spotZh": "嶙峋礁",
    "fish": [
      "pacific-herring",
      "chinook-salmon",
      "lingcod",
      "coho-salmon",
      "masu-salmon"
    ],
    "ice": false
  },
  {
    "id": "ocean1-spot3",
    "order": 14,
    "areaId": "ocean1",
    "area": "Icewater Sea ",
    "areaZh": "冰水海",
    "spot": "Safety Cove",
    "spotZh": "安全湾",
    "fish": [
      "atlantic-salmon",
      "chinook-salmon",
      "steelhead-trout",
      "pink-salmon",
      "american-shad"
    ],
    "ice": false
  },
  {
    "id": "ocean2-spot1",
    "order": 15,
    "areaId": "ocean2",
    "area": "Old Wreck Bay",
    "areaZh": "旧沉船湾",
    "spot": "Divers Drop",
    "spotZh": "潜者渊",
    "fish": [
      "pacific-halibut",
      "striped-bass",
      "sockeye-salmon",
      "dolly-varden",
      "eulachon"
    ],
    "ice": false
  },
  {
    "id": "ocean2-spot2",
    "order": 16,
    "areaId": "ocean2",
    "area": "Old Wreck Bay",
    "areaZh": "旧沉船湾",
    "spot": "Seals Rest",
    "spotZh": "海豹滩",
    "fish": [
      "capelin",
      "striped-bass",
      "greenland-halibut",
      "chum-salmon",
      "dolly-varden"
    ],
    "ice": false
  },
  {
    "id": "ice1-spot1",
    "order": 17,
    "areaId": "ice1",
    "area": "Lake Hunkerdown",
    "areaZh": "屈膝湖",
    "spot": "Frostbite Flats",
    "spotZh": "霜噬台地",
    "fish": [
      "ice-northern-pike",
      "ice-arctic-char",
      "ice-muskie",
      "ice-channel-catfish",
      "ice-largemouth-bass",
      "ice-smallmouth-bass",
      "ice-lake-trout",
      "ice-walleye",
      "ice-tiger-muskie",
      "ice-yellow-perch"
    ],
    "ice": true
  }
];
